services:
  server:
    image: todo-backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: todo-backend-dev # This will name the container hello-front-dev
    environment: 
      # - REDIS_URL=//host.docker.internal:6379
      # - MONGO_URL=mongodb://root:password@host.docker.internal:3456/the_database
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://root:password@mongo:27017/the_database
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  debug-helper:
    image: busybox